<a href="https://colab.research.google.com/github/Marianno77/data-science/blob/main/Uczenie_G%C5%82%C4%99bokie/Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Keras**

## Import bibliotek

In [68]:
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras.activations import linear, sigmoid, relu, tanh
from tensorflow.keras.utils import to_categorical

## Wprowadzenie - pierwszy model

In [4]:
model = Sequential()
print(model)

<Sequential name=sequential, built=False>


In [7]:
model.add(Dense(units=4, input_shape=(10,)))

In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                      │ (None, 4)                   │              44 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.add(Dense(units=2))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                      │ (None, 4)                   │              44 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 2)                   │              10 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

### Funkcje aktywacyjne

In [21]:
random_data = np.linspace(-3, 3, 300)

Linear:

In [22]:
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [16]:
px.line(data, x='data', y='linear')

Sigmoid:

In [18]:
data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [20]:
px.line(data, x='data', y='sigmoid')

Relu:

In [25]:
data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [26]:
px.line(data, x='data', y='relu')

Tanh:

In [28]:
data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [29]:
px.line(data, x='data', y='tanh')

### Model + funkcje aktywacyjne

In [31]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 8)                   │              88 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

### Kompilacja modelu



```
#klasyfikacja binarna:
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

#klasyfikacja wieloklasowa:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

#regresja:
model.compile(optimizer='rmsprop',
              loss='mse')
```



### Trenowanie modelu

In [ ]:
#model.fit(data, labels, epochs=10, validation_split=0.2)

## Klasyfikacja binarna

In [37]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [39]:
data[0]

array([-0.90892548, -1.28636159,  0.38855394,  0.27486804, -0.57385843,
       -0.38495577, -0.37745843,  0.05987019,  1.36536126, -0.94668469,
        0.69408414, -0.09088143,  0.8045959 , -0.7929072 , -0.27622292,
        1.60349227,  0.37633041, -0.06503582,  0.33125549,  0.67078737,
        0.60928044,  1.10139641, -0.76622045,  1.47348472,  0.97541466,
        0.5689101 ,  0.16486871,  1.36313835, -1.11766117,  0.38281308,
        1.12705869,  0.69162175, -0.52185894,  0.25019238, -0.82803948,
       -2.22274306, -0.65844069,  2.09329457, -0.58356357,  0.73953489,
       -1.21119395, -0.44511904, -1.3512265 , -0.16509547, -0.37138346,
       -0.29359487, -1.0700523 ,  0.58221561, -0.98390466, -0.92429118,
        0.385845  ,  0.51629717,  0.83297982,  0.25766051,  0.80980937,
        2.05519636,  0.44553439, -0.29975652,  0.70463482,  0.4229378 ,
       -0.03316619,  0.02130303,  0.440693  ,  0.95499279,  0.0927064 ,
        0.97259489, -0.44192846, -0.37064226, -0.53071753, -0.90

In [40]:
labels[:5]

array([[0],
       [1],
       [1],
       [1],
       [1]])

In [45]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_13 (Dense)                     │ (None, 32)                  │           4,832 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_14 (Dense)                     │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,865 (19.00 KB)

 Trainable params: 4,865 (19.00 KB)

 Non-trainable params: 0 (0.00 B)

In [46]:
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4920 - loss: 0.7733
Epoch 2/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5353 - loss: 0.6980
Epoch 3/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5762 - loss: 0.6717
Epoch 4/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6149 - loss: 0.6570
Epoch 5/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6342 - loss: 0.6438
Epoch 6/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6440 - loss: 0.6343
Epoch 7/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6644 - loss: 0.6166
Epoch 8/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6756 - loss: 0.6069
Epoch 9/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7024 - loss: 0.5882
Epoch 10/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7148 - loss: 0.5737
Epoch 11/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7276 - loss: 0.5557
Epoch 12/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [47]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4925 - loss: 0.7848
Epoch 2/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5328 - loss: 0.7041
Epoch 3/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5638 - loss: 0.6820
Epoch 4/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5916 - loss: 0.6701
Epoch 5/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6101 - loss: 0.6606
Epoch 6/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6263 - loss: 0.6480
Epoch 7/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6400 - loss: 0.6407
Epoch 8/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6539 - loss: 0.6293
Epoch 9/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6756 - loss: 0.6140
Epoch 10/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6847 - loss: 0.6062
Epoch 11/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6979 - loss: 0.5936
Epoch 12/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy

In [48]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5027 - loss: 0.8034 - val_accuracy: 0.4950 - val_loss: 0.7209
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5499 - loss: 0.6905 - val_accuracy: 0.4880 - val_loss: 0.7166
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5878 - loss: 0.6688 - val_accuracy: 0.4905 - val_loss: 0.7179
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6095 - loss: 0.6574 - val_accuracy: 0.4865 - val_loss: 0.7222
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6375 - loss: 0.6428 - val_accuracy: 0.4945 - val_loss: 0.7291
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6587 - loss: 0.6282 - val_accuracy: 0.4945 - val_loss: 0.7336
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6854 - loss: 0.6078 - val_accuracy: 0.4875 - val_loss: 0.7405
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6952 - loss: 0.5952 - val_accuracy: 0.

In [50]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [51]:
metrics = model.history.history
metrics.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [52]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4924 - loss: 0.7795 - val_accuracy: 0.4985 - val_loss: 0.7228
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5367 - loss: 0.6978 - val_accuracy: 0.5050 - val_loss: 0.7182
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5986 - loss: 0.6671 - val_accuracy: 0.5100 - val_loss: 0.7180
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6179 - loss: 0.6574 - val_accuracy: 0.5075 - val_loss: 0.7200
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6452 - loss: 0.6402 - val_accuracy: 0.5185 - val_loss: 0.7243
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6588 - loss: 0.6249 - val_accuracy: 0.5095 - val_loss: 0.7318
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6871 - loss: 0.6062 - val_accuracy: 0.5095 - val_loss: 0.7430
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7033 - loss: 0.5912 - val_accuracy: 0.4995 - val_

In [53]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [54]:
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step


array([[0.11611791],
       [0.31711033],
       [0.66843206],
       [0.34208086],
       [0.6937418 ]], dtype=float32)

In [61]:
np.argmax(model.predict(test_data), axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


array([0, 0, 0, 0, 0])

## Klasyfikacja wieloklasowa

In [69]:
data = np.random.random((10000, 150))
labels = np.random.randint(10, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [70]:
labels[:5]

array([[2],
       [4],
       [9],
       [3],
       [4]])

In [71]:
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [72]:
labels[1]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [73]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.1030 - loss: 2.3440 - val_accuracy: 0.1120 - val_loss: 2.3021
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1088 - loss: 2.3037 - val_accuracy: 0.1070 - val_loss: 2.3031
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1036 - loss: 2.3013 - val_accuracy: 0.1040 - val_loss: 2.3030
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1076 - loss: 2.2997 - val_accuracy: 0.0995 - val_loss: 2.3053
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.1145 - loss: 2.2934 - val_accuracy: 0.1045 - val_loss: 2.3035
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.1163 - loss: 2.2922 - val_accuracy: 0.1025 - val_loss: 2.3082
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.1204 - loss: 2.2897 - val_accuracy: 0.0965 - val_loss: 2.3202
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1306 - loss: 2.2792 - val_accuracy: 0.1050 - val_

In [74]:
test_data = np.random.random((10, 150))
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[0.06147099, 0.07260735, 0.16457932, 0.10029763, 0.06828633,
        0.13568452, 0.12521234, 0.08887661, 0.08559044, 0.0973945 ],
       [0.04532549, 0.05168519, 0.14742279, 0.07890975, 0.11017212,
        0.0801983 , 0.0444275 , 0.18109873, 0.19003223, 0.07072784],
       [0.04617417, 0.04891769, 0.19948955, 0.08103292, 0.07811555,
        0.04758081, 0.0768712 , 0.16312264, 0.12196363, 0.1367319 ],
       [0.04565704, 0.13997704, 0.1444442 , 0.06246016, 0.17474972,
        0.13787127, 0.0982488 , 0.06738407, 0.05470977, 0.07449788],
       [0.0905955 , 0.08085903, 0.08160384, 0.12477467, 0.09522927,
        0.13612653, 0.14248446, 0.053331  , 0.08654476, 0.10845096],
       [0.10186869, 0.1453227 , 0.05665835, 0.08706439, 0.0952056 ,
        0.18948653, 0.06818969, 0.08515279, 0.12966655, 0.04138478],
       [0.06720075, 0.07819942, 0.2258708 , 0.04951951, 0.1075572 ,
        0.09483903, 0.04578793, 0.12418675, 0.13321038, 0.07362818],
       [0.10242994, 0.10884677, 0.0926191

In [77]:
np.argmax(model.predict(test_data), axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


array([2, 8, 2, 4, 6, 5, 2, 6, 5, 8])

## Regresja

In [78]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

print(data.shape)
print(labels.shape)

(10000, 150)
(10000,)


In [79]:
labels[:5]

array([14.04246522, 34.17088677, 44.65808568, 28.37712061, 16.00488285])

In [82]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='linear'))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 384.6047 - val_loss: 215.2471
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 206.5991 - val_loss: 215.1205
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 207.0496 - val_loss: 215.1557
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 206.9372 - val_loss: 215.7506
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 204.7425 - val_loss: 215.9130
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 207.5021 - val_loss: 216.6162
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 201.4172 - val_loss: 216.2537
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 201.0139 - val_loss: 216.7461
Epoch 9/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 203.9782 - val_loss: 216.8987
Epoch 10/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 203.6790 - val_loss: 216.7160
Epoch 11/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 199.3446 - val_loss: 216.6615
Epoch 12/30
250/250

In [83]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='linear'))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14.9160 - mse: 328.8357 - val_loss: 12.7229 - val_mse: 215.7694
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.3079 - mse: 203.8722 - val_loss: 12.7323 - val_mse: 217.1218
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.2074 - mse: 203.1867 - val_loss: 12.7043 - val_mse: 214.9459
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.2249 - mse: 203.5188 - val_loss: 12.7099 - val_mse: 215.1098
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.3121 - mse: 205.8517 - val_loss: 12.7244 - val_mse: 216.0265
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.3109 - mse: 206.2019 - val_loss: 12.7338 - val_mse: 216.0246
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.2749 - mse: 204.2497 - val_loss: 12.7416 - val_mse: 216.3152
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.2009 - mse: 202.3266 - val_loss: 12.7692 - val_mse: 217.3944
Epoch 9/

In [84]:
test_data = np.random.random((10, 150))
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[24.955843],
       [23.656042],
       [23.804945],
       [28.24957 ],
       [24.99252 ],
       [20.168512],
       [25.959328],
       [24.43693 ],
       [26.959856],
       [26.44216 ]], dtype=float32)