<a href="https://colab.research.google.com/github/Marianno77/data-science/blob/main/NumPy/NumPy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# **Algebra liniowa**

## **Norma wektora**

### Norma wektora w R2

In [53]:
v1 = np.array([0, 4])
print(v1)
print(np.linalg.norm(v1))

[0 4]
4.0


### Norma wektora w Rn

In [54]:
v2 = np.array([10, 8, 9])
print(v2)
print(np.linalg.norm(v2))

[10  8  9]
15.652475842498529


## **Odległość dwóch punktów na płaszczyźnie**

In [55]:
p1 = np.array([0, 4])
p2 = np.array([3, 1])
print('punkt p1: ' + str(p1))
print('punkt p2: ' + str(p2))

print('odległość: ' + str(np.linalg.norm(p1 - p2)))


punkt p1: [0 4]
punkt p2: [3 1]
odległość: 4.242640687119285


### Odległość dwóch punktów na płaszczyźnie w Rn

In [56]:
p1 = np.array([0, 4, 5])
p2 = np.array([3, 1, 7])
print('punkt p1: ' + str(p1))
print('punkt p2: ' + str(p2))

print('odległość: ' + str(np.linalg.norm(p1 - p2)))

punkt p1: [0 4 5]
punkt p2: [3 1 7]
odległość: 4.69041575982343


## **Mnożenie macierzy**

### Przykład nr1

In [57]:
A = np.array([[5, 3], [3, 9]])
B = np.array([[1], [-1]])
print('A: \n' + str(A))
print('B: \n' + str(B) + '\n')
print('Wynik mnożenia macierzy: \n' + str(np.dot(A, B)))

A: 
[[5 3]
 [3 9]]
B: 
[[ 1]
 [-1]]

Wynik mnożenia macierzy: 
[[ 2]
 [-6]]


### Przykład nr2

In [58]:
A = np.array([[2 ,-1 ,3], [3, 1, 0]])
B = np.array([[2, 1, -1], [0, -1, 2], [3, 2, 0]])

print('A: \n' + str(A))
print('B: \n' + str(B) + '\n')
print('Wynik mnożenia macierzy: \n' + str(np.dot(A, B)))

A: 
[[ 2 -1  3]
 [ 3  1  0]]
B: 
[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]

Wynik mnożenia macierzy: 
[[13  9 -4]
 [ 6  2 -1]]


## **Wyznacznik macierzy**

In [59]:
A = np.array([[2,4],[-1,3]])
print('A: \n' + str(x) +'\n')
print('wyznacznik macierzy: ' + str(round(np.linalg.det(A))))

A: 
1

wyznacznik macierzy: 10


## **Ślad macierzy**



> Suma przekontnej w macierzy nxn (a11+a22+ann)



In [60]:
A = np.array([[2,4],[-1,3]])
print('A: \n' + str(A) +'\n')
print('ślad macierzy: ' + str(np.trace(A)))

A: 
[[ 2  4]
 [-1  3]]

ślad macierzy: 5


## **Macierz jednostkowa**


> macież nxn , której przekontna jest równa 1



In [61]:
A = np.eye(4, dtype='int')
print('macierz jednostkowa 4x4: \n' + str(A))

macierz jednostkowa 4x4: 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## **Macierz odwrotna**

> A - macierz kwadratowa stopnia n. Macierz A posiada macierz odwrotną, gdy istnieje macierz B, taka że: AB = Ba = I

In [62]:
A = np.array([[2, 4], [-1, 3]])
print('A: \n' + str(A) +'\n')
B = np.linalg.inv(A)
print('macierz odwrotna: \n' + str(B) +'\n')

np.set_printoptions(precision=4, suppress=True)  #ustawienia wyświetlania

print('sprawdzenie AB: \n' + str(np.dot(A, B)))
print('sprawdzenie BA: \n' + str(np.dot(B, A)))

A: 
[[ 2  4]
 [-1  3]]

macierz odwrotna: 
[[ 0.3 -0.4]
 [ 0.1  0.2]]

sprawdzenie AB: 
[[1. 0.]
 [0. 1.]]
sprawdzenie BA: 
[[ 1. -0.]
 [ 0.  1.]]


## **Macierz transponowana**



> Zmiana wierszy na kolumny i kolumn na wiersze



### Przykład nr1

In [63]:
A = np.array([[2, 4], [-1, 3]])
print('A: \n' + str(A) +'\n')
print('transponowana macierz: \n' + str(np.transpose(A)))

A: 
[[ 2  4]
 [-1  3]]

transponowana macierz: 
[[ 2 -1]
 [ 4  3]]


### Przykład nr2

In [64]:
A = np.array([[2, 4, 1], [-1, 3, 7]])
print('A: \n' + str(A) +'\n')
print('transponowana macierz: \n' + str(A.T))

A: 
[[ 2  4  1]
 [-1  3  7]]

transponowana macierz: 
[[ 2 -1]
 [ 4  3]
 [ 1  7]]


## **Rozwiązywanie układów równań**

*   2x+4y=10
*   x-y=-1

In [65]:
A = np.array([[2,4],[1,-1]])
B = np.array([[10],[-1]])

print('A: \n' + str(A) +'\n')
print('B: \n' + str(B) +'\n')

A_inv = np.linalg.inv(A)
print('macierz odwrotna A: \n' + str(A_inv) +'\n')

C = np.dot(A_inv, B)
print('Wynik równania:')

for i in range(len(C)):
  if(i == 0):
    print('x = ' + str(C[i]))
  else:
    print('y = ' + str(C[i]))

A: 
[[ 2  4]
 [ 1 -1]]

B: 
[[10]
 [-1]]

macierz odwrotna A: 
[[ 0.1667  0.6667]
 [ 0.1667 -0.3333]]

Wynik równania:
x = [1.]
y = [2.]
