<a href="https://colab.research.google.com/github/Marianno77/data-science/blob/main/NumPy/NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Biblioteki NumPy**

In [1]:
import numpy as np
np.__version__

'1.26.4'

# **Tablice**

1D

In [ ]:
x = np.array([1,2])
print('Zawartość tablicy: ' + str(x))
print('rozmiar tablicy: ' + str(x.size))

Zawartość tablicy: [1 2]
rozmiar tablicy: 2


2D

In [ ]:
x = np.array([[1,2],[3,4]])
print('Zawartość tablicy: \n' + str(x))
print('rozmiar tablicy: ' + str(x.size))

Zawartość tablicy: 
[[1 2]
 [3 4]]
rozmiar tablicy: 4


3D

In [ ]:


x = np.array(
    [[[1,2,3],
      [4,5,6]],

     [[7,8,9],
      [10,11,12]]]
)
print('Zawartość tablicy: \n' + str(x))
print('rozmiar tablicy: ' + str(x.size))

Zawartość tablicy: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
rozmiar tablicy: 12
8


full, arange, linspace, reshape

In [ ]:
x = np.full((3,3), fill_value=5, dtype='int')
print('Zawartość tablicy: \n' + str(x))

Zawartość tablicy: 
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
x = np.arange(start=1, stop=11)
print('Zawartość tablicy: \n' + str(x))

Zawartość tablicy: 
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
x = np.arange(start=0, stop=11, step=2)
print('Zawartość tablicy: ' + str(x))

Zawartość tablicy: [ 0  2  4  6  8 10]


In [ ]:
x = np.linspace(start=0,stop=10, num=6, dtype='int')
print('Zawartość tablicy: ' + str(x))

Zawartość tablicy: [ 0  2  4  6  8 10]


In [ ]:
x = np.arange(start=1, stop=11)
print('Zawartość tablicy: ' + str(x))
x = x.reshape(2,5)
print('Zawartość tablicy: \n' + str(x))
x = x.reshape(5,-1)
print('Zawartość tablicy: \n' + str(x))

Zawartość tablicy: [ 1  2  3  4  5  6  7  8  9 10]
Zawartość tablicy: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Zawartość tablicy: 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


# Działania na tablicach

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print('Zawartość tablicy a: ' + str(a))
print('Zawartość tablicy b: ' + str(b))
print('tablica a + tablica b = ' + str(a+b))
print('tablica a - tablica b = ' + str(a-b))
print('tablica a * tablica b = ' + str(a*b))
print('tablica a / tablica b = ' + str(a/b))

Zawartość tablicy a: [1 2 3]
Zawartość tablicy b: [4 5 6]
tablica a + tablica b = [5 7 9]
tablica a - tablica b = [-3 -3 -3]
tablica a * tablica b = [ 4 10 18]
tablica a / tablica b = [0.25 0.4  0.5 ]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print('Zawartość tablicy a: ' + str(a))
print('Zawartość tablicy b: ' + str(b))
print('tablica a + tablica b = ' + str(np.add(a,b)))
print('tablica a - tablica b = ' + str(np.subtract(a,b)))
print('tablica a * tablica b = ' + str(np.multiply(a,b)))
print('tablica a / tablica b = ' + str(np.divide(a,b)))

Zawartość tablicy a: [1 2 3]
Zawartość tablicy b: [4 5 6]
tablica a + tablica b = [5 7 9]
tablica a - tablica b = [-3 -3 -3]
tablica a * tablica b = [ 4 10 18]
tablica a / tablica b = [0.25 0.4  0.5 ]


In [ ]:
a = np.array([1,2,3])
print('Zawartość tablicy a: ' + str(a))
print('tablica a + 2 = ' + str(a+2))
print('tablica a - 2 = ' + str(a-2))
print('tablica a * 2 = ' + str(a*2))
print('tablica a / 2 = ' + str(a/2))

Zawartość tablicy a: [1 2 3]
tablica a + 2 = [3 4 5]
tablica a - 2 = [-1  0  1]
tablica a * 2 = [2 4 6]
tablica a / 2 = [0.5 1.  1.5]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print('Zawartość tablicy a: \n' + str(a))
print('Zawartość tablicy b: \n' + str(b))
print('tablica a + tablica b = \n' + str(np.add(a,b)))
print('tablica a - tablica b = \n' + str(np.subtract(a,b)))
print('tablica a * tablica b = \n' + str(np.multiply(a,b)))
print('tablica a / tablica b = \n' + str(np.divide(a,b)))

Zawartość tablicy a: 
[[1 2]
 [3 4]]
Zawartość tablicy b: 
[[5 6]
 [7 8]]
tablica a + tablica b = 
[[ 6  8]
 [10 12]]
tablica a - tablica b = 
[[-4 -4]
 [-4 -4]]
tablica a * tablica b = 
[[ 5 12]
 [21 32]]
tablica a / tablica b = 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print('Zawartość tablicy a: \n' + str(a))
print('Zawartość tablicy b: \n' + str(b))
print('mnożenie macierzy a⋅b, zgodnie z zasadami algebry liniowej: \n' + str(np.dot(a,b)))
print('mnożenie macierzy b⋅a, zgodnie z zasadami algebry liniowej: \n' + str(a.dot(b)))
print('mnożenie macierzy a⋅b, zgodnie z zasadami algebry liniowej: \n' + str(a@b))

Zawartość tablicy a: 
[[1 2]
 [3 4]]
Zawartość tablicy b: 
[[5 6]
 [7 8]]
mnożenie macierzy a⋅b, zgodnie z zasadami algebry liniowej: 
[[19 22]
 [43 50]]
mnożenie macierzy b⋅a, zgodnie z zasadami algebry liniowej: 
[[19 22]
 [43 50]]
mnożenie macierzy a⋅b, zgodnie z zasadami algebry liniowej: 
[[19 22]
 [43 50]]


# Generowanie liczb losowych

In [ ]:
np.random.randint(10)

0

In [ ]:
#generowanie tych samych liczb losowych
np.random.seed(0)

np.random.randint(10)

5

generowanie liczb z przedziału

In [ ]:
np.random.randint(low=5, high=10)

5

automatycznie generowanie tablicy wypełnionej losowymi liczbami

In [ ]:
np.random.randint(low=5, high=10, size=5)

array([8, 8, 8, 6, 8])

losowanie elementu z tablicy

In [ ]:
np.random.choice(['jeden', 'dwa', 'trzy'])

'dwa'

losowe tasownaie elementów tablicy

In [ ]:
x = np.arange(10)
print('zawartość tablicy x: ' + str(x))
np.random.shuffle(x)
print('zawartość potasowanej tablicy x: ' + str(x))

zawartość tablicy x: [0 1 2 3 4 5 6 7 8 9]
zawartość potasowanej tablicy x: [3 1 9 8 5 0 6 7 4 2]


# Elementy tablicy

In [ ]:
x = np.arange(10)
print('zawartość tablicy x: ' + str(x))
print('trzeci element tablicy x: ' + str(x[3]))
print('elementy tablicy x od 2 do 4: ' + str(x[1:3]))
print('elementy tablicy x od 2: ' + str(x[1:]))
print('elementy tablicy x do 4: ' + str(x[:3]))

zawartość tablicy x: [0 1 2 3 4 5 6 7 8 9]
trzeci element tablicy x: 3
elementy tablicy x od 2 do 4: [1 2]
elementy tablicy x od 2: [1 2 3 4 5 6 7 8 9]
elementy tablicy x do 4: [0 1 2]


In [ ]:
x = np.arange(10)
x = x.reshape(2,5)
print('Zawartość tablicy x: \n' + str(x))

print('pierwszy wiersz tablicy x: ' + str(x[0]))
print('pierwsza kolumna tablicy x: '  + str(x[:,0]))
print('element (1,2) tablicy x: ' + str(x[1][2]))

Zawartość tablicy x: 
[[0 1 2 3 4]
 [5 6 7 8 9]]
pierwszy wiersz tablicy x: [0 1 2 3 4]
pierwsza kolumna tablicy x: [0 5]
element (1,2) tablicy x: 7


# Maski logiczne

In [4]:
x = np.arange(start=-10, stop=10.5, step=0.5)
print('Zawartość tablicy x: ' + str(x))

Zawartość tablicy x: [-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5
  -4.   -3.5  -3.   -2.5  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5
   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5   7.    7.5
   8.    8.5   9.    9.5  10. ]


sprawdzanie które elementy są dodatnie

In [10]:
print(x > 0)

[False False False False False False False False False False False False
 False False False False False False False False False  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True]


wypisywanie tych liczb

In [11]:
print(x[x > 0])

[ 0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5 10. ]


dwa warunki, (przedział)

In [9]:
print(np.bitwise_and(x > -5 , x < 5))

[False False False False False False False False False False False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False False False False False False
 False False False False False]


In [12]:
print(x[np.bitwise_and(x > -5 , x < 5)])

[-4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.
  2.5  3.   3.5  4.   4.5]
